### PR TITLE
TPP-00103: Catch exceptions and errors and rerender or re-call APIs upon failure

### LINKED ISSUE #103: TPP-00103: Catch exceptions and errors and rerender or re-call APIs upon failure
> As a user, when an error happens in rendering, instead of a blank screen render the error screen, and when an error happens in Service API calls, retry using a modal. 

This guide is really helpful: 
https://elazizi.com/handling-errors-in-react-native-a-complete-guide

### PR DESCRIPTION
**Pull request by faye-tan**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue/ticket number)
#103

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by yichenesia** [comment]
I think `package-lock.json` and `package.json` needs to be committed 😩

**Comment by yichenesia** [comment]
Is there some programmatic way to trigger an error? I was trying to test if the error modal pops up but I'm really not sure how to ;-;

**Review by yichenesia — CHANGES_REQUESTED** [review]
I think it looks fine, I wasn't sure how to test the error modal popping up, but it seems to be correct from just checking the structure of how it's applied to the code.

The only request change from me is to add package.json and package-lock.json since `react-native-restart` was missing when doing `npm install` ;-;

File: tpp-app/src/services/cycle/CycleService.js [hunk 1]
```diff
@@ -20,24 +21,25 @@ import isAfter from 'date-fns/isAfter';
  * @return {Promise} Resolves into Date object that is the closest date after finalPeriodStart that is the end of a period. Date may be in a later year than finalPeriodStart
  */
 async function getLastPeriodsEnd(finalPeriodStart, calendar = null){
+  try {
     var current = finalPeriodStart;
     var yesterday = subDays(current, 1);
     var twoDaysEarlier = subDays(current, 2);
```
Comment (yuemily24) [inline tpp-app/src/services/cycle/CycleService.js]: Can we avoid using `var`? it's globally scoped

File: tpp-app/src/services/cycle/CycleService.js [hunk 2]
```diff
@@ -20,24 +21,25 @@ import isAfter from 'date-fns/isAfter';
...
-    let dateSymptoms = getSymptomsFromCalendar(calendar, current.getDate(), current.getMonth()+1, current.getFullYear());
+    let dateSymptoms = getSymptomsFromCalendar(calendar, current.getDate(), current.getMonth() + 1, current.getFullYear());
     let yesterdaySymptoms = new Symptoms();
     let twoDaysEarlierSymptoms = new Symptoms()
 
-    var noFlowToday = (dateSymptoms.flow === FLOW_LEVEL.NONE || dateSymptoms.flow === null) ;
-    var noFlowYesterday = (yesterdaySymptoms.flow === FLOW_LEVEL.NONE || yesterdaySymptoms.flow === null) ;
+    var noFlowToday = (dateSymptoms.flow === FLOW_LEVEL.NONE || dateSymptoms.flow === null);
+    var noFlowYesterday = (yesterdaySymptoms.flow === FLOW_LEVEL.NONE || yesterdaySymptoms.flow === null);
     var flowTwoDaysEarlier = (twoDaysEarlierSymptoms.flow !== null && twoDaysEarlierSymptoms.flow !== FLOW_LEVEL.NONE)
```
Comment (yuemily24) [inline tpp-app/src/services/cycle/CycleService.js]: same here `var` to `let`

File: tpp-app/src/services/cycle/CycleService.js [hunk 3]
```diff
@@ -69,25 +72,30 @@ export {getLastPeriodsEnd};
 
 async function isOnPeriod (calendar = null) {
 
-  let current = await this.GETMostRecentPeriodStartDate(calendar) // most recent period start date
+  try {
+    let current = await this.GETMostRecentPeriodStartDate(calendar) // most recent period start date
 
-  var yesterday = subDays(current, 1);
+    var yesterday = subDays(current, 1);
```
Comment (yuemily24) [inline tpp-app/src/services/cycle/CycleService.js]: There's a lot of instances of `var` tbh LOL. At this point it might take a big Ctrl+F whole repo. It's not a big deal though as long as it's not breaking anything.

**Review by yuemily24 — APPROVED** [review]
I couldn't run it but I trust that everything is working. Codewise, everything looks good, just a small comment on how `var` isn't good because it's globally scoped. But at this point, if everything is running it's not an issue.

File: tpp-app/src/services/cycle/CycleService.js (hunk 1 above)
Comment (faye-tan) [reply tpp-app/src/services/cycle/CycleService.js]: yes! good point

File: tpp-app/src/services/cycle/CycleService.js (hunk 2 above)
Comment (faye-tan) [reply tpp-app/src/services/cycle/CycleService.js]: oui

**Comment by faye-tan** [comment]
> Is there some programmatic way to trigger an error? I was trying to test if the error modal pops up but I'm really not sure how to ;-;

@yichenesia throw new Error("react native why") inside of a service file

File: tpp-app/src/services/cycle/CycleService.js (hunk 3 above)
Comment (faye-tan) [reply tpp-app/src/services/cycle/CycleService.js]: made changes! except for notification files since Edward is still working on those

**Review by yichenesia — APPROVED** [review]
