### PR TITLE
TPP-00045: quick log vs. multiple log and Info screen bug fixes

### LINKED ISSUE #45: TPP-00045: quick log vs. multiple log
> As a user of Menstruation Nation, I want to be able to quick log for today and log multiple days at once

**Technical Information:**
- Change icon in red circle to "+" icon when user is on month view instead of drop icon
- tapping "+" icon will bring up two buttons "Log daily symptoms" with drop icon and "Log multiple period dates" with calendar icon. The "+" icon also turns to an "X" icon
- grey overlay while two buttons "Log daily symptoms" with drop icon and "Log multiple period dates" with calendar icon appear. Tapping "X" on red button will close the two white buttons, tapping anywhere on gray overlay will also close the two buttons. When buttons close "X" icon turns back into a "+" 
- Tapping on "Log daily symptoms" brings up symptom panel 
- Tapping on "Log multiple period dates" brings up a teal bar overtop the month view that says "Tap dates to log period", please use "dates" not "date" 
  - Nothing happens when you tap dates for now
  - Add x button on top left so you can exit out of this view
  - Don't need to add the green checkmark button for now

**Styling Requirements:**
Screen Shot 2021-12-22 at 2 44 26 PM
Screen Shot 2021-12-27 at 4 14 29 PM

Screen Shot 2021-12-22 at 2 29 23 PM
- don't follow text in image follow what I say hehe 
- "Log daily symptoms" with drop icon and "Log multiple period dates" with calendar icon 
- Text should be on the RIGHT side of buttons instead of LEFT side in image 😓

### PR DESCRIPTION
**Pull request by yuemily24**
# Description

@kenneth-miura @faye-tan @yichenesia @roylin2000  I rebased multiple times so I'm worried some recent changes and migrations might've disappeared. Can you review my code and make sure everything matches the `develop` branch? I tried to keep everything the same as much as I could. 

## Quick log vs. Multiple log

New `SelectLogOptionOverlay` screen that lets you pick between quick logging daily symptoms and logging for multiple days.

This ticket includes several new files. I also cleaned up a lot of old code and made them into components. Here's a breakdown:

- move `CustomTabBarButton` now known as `TabBarMiddleButton` from `app.js` to the components directory
    - There was way too much code for this button taking up space in `app.js`, especially once I added animations and helper functions.
- `CalendarNavigator` has 3 new screens: `SelectLogOptionOverlay`, `LogSymptomsScreen`, and `LogMultipleDatesScreen`
    - `SelectLogOptionOverlay` has a reusable button component which I put in `LoggingOptionButton.js`

Screen Shot 2022-01-30 at 10 55 54 PM
Screen Shot 2022-01-30 at 10 56 03 PM

Fixes #56 TPP-00045

## Extra Info Screen Changes
Once I did my merging, I noticed a lot of breaking changes in `InfoNavigator` and on the `Info.js` screen. So I refactored some of the code and did some bug fixes:
- Fixed `InfoNavigator` not being called by the `Tab.Navigator`
- Fixed some identical screen names which is bad practice
- Map `cardData` to `MenstrualProductCard` instead of typing up an instance of each. Code should be a lot cleaner
- Fixed issue where some icons weren't centering on `MenstrualProductCard`
- Added some styling so that cards are spaced out more evenly

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by edwardhuahan — APPROVED** [review]
Wow this is great! Your code is so well organized

File: tpp-app/src/info/Info.js [hunk 1]
```diff
@@ -10,56 +10,80 @@ const LearnMoreCard = () => {
...
-        color: "#6D6E71",
-        margin: 15}}>Learn more about period products</Text>
+                <Text style={{
+                    ...styles.productText,
+                    textAlign: 'left',
+                    color: "#6D6E71",
+                    margin: 15
+                }}>
+                    Learn more about period products
+                </Text>
```
Comment (roylin2000) [inline tpp-app/src/info/Info.js:75]: Love this!

File: tpp-app/src/home/components/TabBarMiddleButton.js [hunk 2]
```diff
@@ -0,0 +1,130 @@
+import React, { useRef, useEffect, useState } from 'react';
+import { StyleSheet, TouchableOpacity, Animated, Easing } from 'react-native';
+import { useIsFocused, useNavigation } from '@react-navigation/native';
+import VectorImage from 'react-native-vector-image';
```
Comment (roylin2000) [inline tpp-app/src/home/components/TabBarMiddleButton.js]: There is a merge conflict with the develop branch because it's now using the new SVG package rather than this one, so if you change this and just accept the changes from your branch then you should be all good!

File: tpp-app/src/home/components/TabBarMiddleButton.js [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+
+export const TabBarMiddleButton = ({ onPress }) => {
+  const navigation = useNavigation();
+  const calendarShowing = useIsFocused();
+  const [rotate, setRotation] = useState(0); // see RotateView for more info
+
+  // set icon and background color based on if the calendar screen is focused
+  let icon = calendarShowing
+    ? <VectorImage source={require('../../../ios/tppapp/Images.xcassets/icons/plus_sign.svg')}/>
+    : <VectorImage source={require('../../../ios/tppapp/Images.xcassets/icons/calendar_icon.svg')} />;
```
Comment (roylin2000) [inline tpp-app/src/home/components/TabBarMiddleButton.js]: Related to the above comment about merge conflict.

**Review by roylin2000 — CHANGES_REQUESTED** [review]
Merge conflict due to using new SVG package, if you could switch to the new one it would save some time in the future :D

File: tpp-app/src/home/pages/CalendarScreen.js [hunk 4]
```diff
@@ -61,19 +88,25 @@ const Calendar = () => {
...
-                        width={sideComponentWidth}
-                    />
-                </View>
+                {/*<BackButton
+                    onPress={() => {
+                        navigation.navigate('Year')
+                    }}
+                    title='Year'
+                    width={sideComponentWidth}
+                />*/}
```
Comment (faye-tan) [inline tpp-app/src/home/pages/CalendarScreen.js:109]: this reminds me we need to get rid of the unused blank year page stuff lol - but we'll do that in another story 😅

**Comment by faye-tan** [comment]
Wow thanks @yuemily24  for fixing so much stuff that was out of scope! I ran this branch and nothing broke for me - also went through the code and looks good to me! Some small things our code base could use improvement on:

Regarding identical screen names: yes this is bad, and rn a lot of it is hard coded. I think we should move to using constants for the screen names (https://www.bigbinary.com/learn-react-native/navigation-best-practices), for example: 
```
export const Navigation_Routes = {
  MIDDLE_BUTTON: "Middle Button", 
  LOG_SYMPTOMS: "Log Symptoms", 
  LOG_MULTIPLE_DATES: "Log Multiple Dates", 
  CALENDAR: "Calendar", 
  INFO: "Info", 
  ...
}
```
This will also keep a centralized list of all our routes and screens which may help in duplicated naming. 

A CTRL+F search of "navigation.navigate" reveals all the hard coded values that if mistyped could go badly! So instead of ```navigation.navigate('MiddleButton')``` let's have ```navigation.navigate(Navigation_Routes.MIDDLE_BUTTON)``` and instead of ```<Tab.Screen name="MiddleButton" ...``` let's have ```<Tab.Screen name={Navigation_Routes.MIDDLE_BUTTON} ...```

But you've done a lot here, these are not within the scope of your issue, so I will create new issues for these 😄

**Review by faye-tan — APPROVED** [review]
🤞 massive rebase job but i ran it and looks ok to me!

**Review by kenneth-miura — APPROVED** [review]
Will keep it 100 I only in-depth read the stuff from the selector PR + SVG library migration PR. It's successfully using the new SVG lib, and the functionality from the selector PR is all there. It's positioned a bit weirdly rn b/c of back button removal, but faye said that'll be a separate story.

**Review by roylin2000 — APPROVED** [review]
Everything looks good!
